"""add org management fields

Revision ID: 1a2b3c4d5e6f
Revises: f89239b21f04
Create Date: 2026-05-31 17:50:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = 'f89239b21f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    
    op.drop_column('organizations', 'is_active')
    op.drop_column('organizations', 'slug')
    op.drop_column('organizations', 'name')
    # ### end Alembic commands ###
